### ISSUE TITLE
Create mulled container that can be used for the PEPTIDE_PREDICTION

### ISSUE THREAD

**Issue by marissaDubbelaar** [nf-core/epitopeprediction#91]
The current workflow runs with the following tools (and versions)

MultiQC v1.6
CSVTK v0.19.1
SNPsift v4.3t
Fred2 v2.0.7
MHCFlurry v1.4.3
MHCnuggets v2.3.2

**Comment by jonasscheid** [comment]
This PR has been removed and a new one has been created under [#1931](https://github.com/BioContainers/multi-package-containers/pull/1931). Waiting for approval

**Comment by jonasscheid** [comment]
[#1931](https://github.com/BioContainers/multi-package-containers/pull/1931) was closed and we agreed on temporary working with the already [existing container](https://github.com/BioContainers/multi-package-containers/pull/1615/commits/a753f7057c2a00d669c4e9f86563899a1f767aa3) with fred2=2.0.6 instead of fred2=2.0.7

**Comment by jonasscheid** [comment]
A mulled container has been created with
- snpsift=4.3.1t
- python=2.7.15
- pyvcf=0.6.8
- pandas=0.24.2
- fred2=2.0.7
- mhcflurry=1.4.3
- mhcnuggets=2.3.2

 in [#1933](https://github.com/BioContainers/multi-package-containers/pull/1933)

**Comment by marissaDubbelaar** [comment]
It will be available as:
quay.io/biocontainers/mulled-v2-c3f301504f7fa2e7bf81c3783de19a9990ea3001:12b1b9f040fd92a80629d58f8a558dde4820eb15-0

Needs to be build first though 😉
